server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_comehome?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 111
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL
logging:
  level:
    com.ef.comehome: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error

file:
  path:
    head: http://120.26.177.155/

swagger:
  enabled: true
  version: 1.0.0


fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 120.26.177.155:22122
